baseURL = 'https://coffeeandtech.blog/'
languageCode = 'en-us'
defaultContentLanguage = "en-gb"
title = 'Technology...while drinking coffee'



[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[caches]
  [caches.images]
    dir = ':cacheDir/images'



[[params.socialIcons]]
name = "github"
url = "https://github.com/coffeeandtech"
